CREATE TABLE [User] (
    UserId INT PRIMARY KEY IDENTITY(1,1),
    UserName VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    UserType VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE
);
